//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD.UploadImageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadService", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UploadService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPath", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetPath : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PathName {
            get {
                return this.PathNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PathNameField, value) != true)) {
                    this.PathNameField = value;
                    this.RaisePropertyChanged("PathName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UploadImageService.UploadService1Soap")]
    public interface UploadService1Soap {
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileToByteArray", ReplyAction="*")]
        CRUD.UploadImageService.FileToByteArrayResponse FileToByteArray(CRUD.UploadImageService.FileToByteArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileToByteArray", ReplyAction="*")]
        System.Threading.Tasks.Task<CRUD.UploadImageService.FileToByteArrayResponse> FileToByteArrayAsync(CRUD.UploadImageService.FileToByteArrayRequest request);
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        CRUD.UploadImageService.UploadFileResponse UploadFile(CRUD.UploadImageService.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<CRUD.UploadImageService.UploadFileResponse> UploadFileAsync(CRUD.UploadImageService.UploadFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileToByteArrayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileToByteArray", Namespace="http://tempuri.org/", Order=0)]
        public CRUD.UploadImageService.FileToByteArrayRequestBody Body;
        
        public FileToByteArrayRequest() {
        }
        
        public FileToByteArrayRequest(CRUD.UploadImageService.FileToByteArrayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FileToByteArrayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public FileToByteArrayRequestBody() {
        }
        
        public FileToByteArrayRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FileToByteArrayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FileToByteArrayResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRUD.UploadImageService.FileToByteArrayResponseBody Body;
        
        public FileToByteArrayResponse() {
        }
        
        public FileToByteArrayResponse(CRUD.UploadImageService.FileToByteArrayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FileToByteArrayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRUD.UploadImageService.UploadService FileToByteArrayResult;
        
        public FileToByteArrayResponseBody() {
        }
        
        public FileToByteArrayResponseBody(CRUD.UploadImageService.UploadService FileToByteArrayResult) {
            this.FileToByteArrayResult = FileToByteArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFile", Namespace="http://tempuri.org/", Order=0)]
        public CRUD.UploadImageService.UploadFileRequestBody Body;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(CRUD.UploadImageService.UploadFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] byteArr;
        
        public UploadFileRequestBody() {
        }
        
        public UploadFileRequestBody(string fileName, byte[] byteArr) {
            this.fileName = fileName;
            this.byteArr = byteArr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRUD.UploadImageService.UploadFileResponseBody Body;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(CRUD.UploadImageService.UploadFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRUD.UploadImageService.GetPath UploadFileResult;
        
        public UploadFileResponseBody() {
        }
        
        public UploadFileResponseBody(CRUD.UploadImageService.GetPath UploadFileResult) {
            this.UploadFileResult = UploadFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UploadService1SoapChannel : CRUD.UploadImageService.UploadService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadService1SoapClient : System.ServiceModel.ClientBase<CRUD.UploadImageService.UploadService1Soap>, CRUD.UploadImageService.UploadService1Soap {
        
        public UploadService1SoapClient() {
        }
        
        public UploadService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UploadService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRUD.UploadImageService.FileToByteArrayResponse CRUD.UploadImageService.UploadService1Soap.FileToByteArray(CRUD.UploadImageService.FileToByteArrayRequest request) {
            return base.Channel.FileToByteArray(request);
        }
        
        public CRUD.UploadImageService.UploadService FileToByteArray(string fileName) {
            CRUD.UploadImageService.FileToByteArrayRequest inValue = new CRUD.UploadImageService.FileToByteArrayRequest();
            inValue.Body = new CRUD.UploadImageService.FileToByteArrayRequestBody();
            inValue.Body.fileName = fileName;
            CRUD.UploadImageService.FileToByteArrayResponse retVal = ((CRUD.UploadImageService.UploadService1Soap)(this)).FileToByteArray(inValue);
            return retVal.Body.FileToByteArrayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRUD.UploadImageService.FileToByteArrayResponse> CRUD.UploadImageService.UploadService1Soap.FileToByteArrayAsync(CRUD.UploadImageService.FileToByteArrayRequest request) {
            return base.Channel.FileToByteArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRUD.UploadImageService.FileToByteArrayResponse> FileToByteArrayAsync(string fileName) {
            CRUD.UploadImageService.FileToByteArrayRequest inValue = new CRUD.UploadImageService.FileToByteArrayRequest();
            inValue.Body = new CRUD.UploadImageService.FileToByteArrayRequestBody();
            inValue.Body.fileName = fileName;
            return ((CRUD.UploadImageService.UploadService1Soap)(this)).FileToByteArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRUD.UploadImageService.UploadFileResponse CRUD.UploadImageService.UploadService1Soap.UploadFile(CRUD.UploadImageService.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public CRUD.UploadImageService.GetPath UploadFile(string fileName, byte[] byteArr) {
            CRUD.UploadImageService.UploadFileRequest inValue = new CRUD.UploadImageService.UploadFileRequest();
            inValue.Body = new CRUD.UploadImageService.UploadFileRequestBody();
            inValue.Body.fileName = fileName;
            inValue.Body.byteArr = byteArr;
            CRUD.UploadImageService.UploadFileResponse retVal = ((CRUD.UploadImageService.UploadService1Soap)(this)).UploadFile(inValue);
            return retVal.Body.UploadFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRUD.UploadImageService.UploadFileResponse> CRUD.UploadImageService.UploadService1Soap.UploadFileAsync(CRUD.UploadImageService.UploadFileRequest request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRUD.UploadImageService.UploadFileResponse> UploadFileAsync(string fileName, byte[] byteArr) {
            CRUD.UploadImageService.UploadFileRequest inValue = new CRUD.UploadImageService.UploadFileRequest();
            inValue.Body = new CRUD.UploadImageService.UploadFileRequestBody();
            inValue.Body.fileName = fileName;
            inValue.Body.byteArr = byteArr;
            return ((CRUD.UploadImageService.UploadService1Soap)(this)).UploadFileAsync(inValue);
        }
    }
}
